### PR TITLE
Hello-Microverse-Project

### PR DESCRIPTION
**Pull request by danutibe07**

### CODE REVIEW

**Review by iambenkis — COMMENTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @danutibe07   👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark: 
- Descriptive PR :heavy_check_mark: 



 ## Required Changes ♻️

- [x]  Good job setting up your README file but, I noticed that you add something that shouldn't be there , in the [author's](https://github.com/danutibe07/Hello-Microverse-Project/tree/feauture#-authors-) section you add microverse while you are the only author, :1st_place_medal:  Kindly remove that, and you will be read to go 

Screenshot from 2023-01-11 03-13-47


- [ ] [**IMPORTANT NOTE**] **Next time :next_track_button:  note that you are not allowed to merge your branched unless you get approved by a code reviewer, It is an important step you should always follow at microverse.** :smiley: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danutibe07** [comment]
@iambenkis  I just made the changes can you please check it before I request a review or do I have to always request a review

**Comment by danutibe07** [comment]
[https://github.com/danutibe07/Hello-Microverse-Project/pull/1](work)     @iambenkis

**Comment by iambenkis** [comment]
Ask again for a review

**Pull request merged**
